name: Release to Maven Central (New API)

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Sprisk Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and publish to local Maven repo
        run: ./gradlew clean build publishToMavenLocal
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare Central Upload Bundle
        run: |
          TARGET_DIR=$(find ~/.m2/repository/io/github/sahinemirhan/ -type d -name "0.0.*" | head -n 1)
          echo "Packaging artifacts from $TARGET_DIR"
          cd "$TARGET_DIR"
          # MD5 ve SHA1 checksum dosyalarını oluştur
          for f in *.*; do
            if [[ "$f" != *.md5 && "$f" != *.sha1 && "$f" != *.asc ]]; then
              md5sum "$f" | awk '{print $1}' > "$f.md5"
              sha1sum "$f" | awk '{print $1}' > "$f.sha1"
            fi
          done
          zip -r /tmp/sprisk-bundle.zip ./*
          echo "✅ Bundle ready: /tmp/sprisk-bundle.zip"

      - name: Upload to Central Publisher API
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: |
          echo "🚀 Uploading to Maven Central..."
          curl -u "$CENTRAL_USERNAME:$CENTRAL_PASSWORD" \
               -F "bundle=@/tmp/sprisk-bundle.zip" \
               -F "publishingType=AUTOMATIC" \
               https://central.sonatype.com/api/v1/publisher/upload

