name: Release to Maven Central (New API)

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Sprisk Engine (Core + Starter)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and publish to local Maven repo
        run: ./gradlew clean build publishToMavenLocal
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare Central Upload Bundle
        run: |
          echo "📦 Preparing bundle..."
          ZIP_PATH="/tmp/sprisk-bundle.zip"
          touch "$ZIP_PATH"
          
          # Tüm modülleri (core + starter) sırayla ekle
          for moduleDir in $(find ~/.m2/repository/io/github/sahinemirhan/ -type d -regex ".*/0\\.0\\..*"); do
            echo "Adding artifacts from $moduleDir"
            cd "$moduleDir"
            for f in *.*; do
              if [[ "$f" != *.md5 && "$f" != *.sha1 && "$f" != *.asc ]]; then
                md5sum "$f" | awk '{print $1}' > "$f.md5"
                sha1sum "$f" | awk '{print $1}' > "$f.sha1"
              fi
            done
            zip -j -u "$ZIP_PATH" ./*
          done

          echo "✅ Bundle ready at $ZIP_PATH"

      - name: Upload to Central Publisher API
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: |
          echo "🚀 Uploading to Maven Central..."
          curl -u "$CENTRAL_USERNAME:$CENTRAL_PASSWORD" \
               -F "bundle=@/tmp/sprisk-bundle.zip" \
               -F "publishingType=AUTOMATIC" \
               https://central.sonatype.com/api/v1/publisher/upload
