name: Release to Maven Central (New API)

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Sprisk Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and publish to local Maven repo
        run: ./gradlew clean build publishToMavenLocal
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload to Central Publisher API
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: |
          echo "🔍 Searching for built artifacts..."
          ARTIFACT_PATH=$(find ~/.m2/repository/io/github/sahinemirhan/ -name "*.jar" | head -n 1 | xargs dirname)
          echo "📦 Uploading contents of $ARTIFACT_PATH"
          zip -r sprisk-artifacts.zip $ARTIFACT_PATH

          echo "🚀 Sending to Central API..."
          curl -u "$CENTRAL_USERNAME:$CENTRAL_PASSWORD" \
               -F "bundle=@sprisk-artifacts.zip" \
               -F "publishingType=AUTOMATIC" \
               https://central.sonatype.com/api/v1/publisher/upload
